uicc0 = {
  imsi = "001010123456789";
  key = "96D2E48AB066384D0C61828F2B2FE5E3";
  opc = "1185B494BDAC5B7909DEE705B017F165";
  dnn = "internet";
  nssai_sst = 1;
  nssai_sd = 0xffffff;
}

log_config = {
  global_log_level = "info";
  phy_log_level = "info";
  mac_log_level = "info";
  rlc_log_level = "info";
  pdcp_log_level = "info";
  rrc_log_level = "info";
  nas_log_level = "info";
};
