mcc: '001'
mnc: '01'
nci: '0x000000010'
idLength: 32
tac: 1
linkIp: 10.3.0.1
ngapIp: 10.3.0.1
gtpIp: 10.3.0.1

amfConfigs:
  - address: 10.3.0.2
    port: 38412

slices:
  - sst: 1

ignoreStreamIds: true
